addSbtPlugin("de.heikoseeberger"         % "sbt-header"    % "5.4.0")
addSbtPlugin("com.github.tkawachi"       % "sbt-doctest"   % "0.9.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.2.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.6.1")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"       % "0.3.7")
